# ETL SRAG
library(readr)
srag <- read_csv2(file = "https://gitlab.procc.fiocruz.br/mave/repo/raw/master/Dados/InfoGripe/dados_semanais_faixa_etaria_sexo_virus.csv", col_types = cols(
  .default = col_double(),
  `data de publicação` = col_date(format = ""),
  UF = col_character(),
  `Unidade da Federação` = col_character(),
  Tipo = col_character(),
  dado = col_character(),
  escala = col_character(),
  sexo = col_character(),
  `Ano epidemiológico` = col_integer(),
  `Semana epidemiológica` = col_integer(),
  `Ano e semana epidemiológica` = col_character(),
  `Situação do dado` = col_character(),
  `Total reportado até a última atualização` = col_number(),
  `Idade desconhecida` = col_number(),
  `< 2 anos` = col_number(),
  `0-4 anos` = col_number(),
  `10-19 anos` = col_number(),
  `2-4 anos` = col_number(),
  `20-29 anos` = col_number(),
  `30-39 anos` = col_number(),
  `40-49 anos` = col_number(),
  `5-9 anos` = col_number(),
  `50-59 anos` = col_number(),
  `60+ anos` = col_number(),
  `Testes positivos` = col_number(),
  `Testes negativos` = col_number(),
  `Casos aguardando resultado` = col_number(),
  `Casos sem informação laboratorial` = col_number(),
  `Casos sem teste laboratorial` = col_number(),
  `Influenza A` = col_number(),
  `Influenza B` = col_number(),
  `SARS-CoV-2` = col_number(),
  `Vírus sincicial respiratório (VSR)` = col_number(),
  `Parainfluenza 1` = col_number(),
  `Parainfluenza 2` = col_number(),
  `Parainfluenza 3` = col_number(),
  `Adenovirus` = col_number()
  ))
